import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModelProvider } from "@/context/modelContext";
import Header from "./ui/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black text-white `}>
        <Header />
        <ModelProvider>{children}</ModelProvider>
      </body>
    </html>
  );
}
